version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    container_name: banco-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: banco_user
      POSTGRES_PASSWORD: banco_pass
      POSTGRES_DB: banco_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: banco-api
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: banco_user
      DATABASE_PASSWORD: banco_pass
      DATABASE_NAME: banco_db
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  pgdata:
